trigger:
- main

pool:
  name: default

variables:
  buildConfiguration: 'Release'
  projectPath: 'src/finance-control.Api/finance-control.Api.csproj'
  publishDestination: 'C:\Users\Mateus\Desktop\Publish'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build API (.NET 9)'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publicar API (.NET 9) diretamente no destino'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output "$(publishDestination)" --no-self-contained'
    zipAfterPublish: false

