trigger:
- main

pool:
  name: default

variables:
  buildConfiguration: 'Release'
  # Alterado para apontar para a solução
  solutionPath: 'finance-control.sln' # <-- ASSUMINDO O NOME E LOCALIZAÇÃO
  projectPath: 'src/finance-control.Api/finance-control.Api.csproj'
  publishDestination: 'C:\Users\Mateus\Desktop\Publish'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes'
  inputs:
    command: 'restore'
    projects: '$(solutionPath)' # Restaurar para a solução inteira

- task: DotNetCoreCLI@2
  displayName: 'Build Solução'
  inputs:
    command: 'build'
    projects: '$(solutionPath)' # Buildar a solução inteira
    arguments: '--configuration $(buildConfiguration)'

# ETAPA MODIFICADA - A SOLUÇÃO DEFINITIVA
- task: DotNetCoreCLI@2
  displayName: 'Publicar API (.NET 9) diretamente no destino'
  inputs:
    command: 'publish'
    # IMPORTANTE: Mantenha publishWebProjects como false
    publishWebProjects: false
    # Aponte para o projeto que você quer publicar
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output "$(publishDestination)"'
    # IMPORTANTE: Desmarque a opção de criar uma pasta com o nome do projeto
    modifyOutputPath: false # <-- ESTA É A OPÇÃO MÁGICA!
