trigger:
- main

pool:
  name: default

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  outputFolder: '$(Agent.WorkFolder)/_build_output'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Compilar API (.NET 9)'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publicar API (.NET 9)'
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(outputFolder)'

- task: PublishBuildArtifacts@1
  displayName: 'Publicar Artefatos'
  inputs:
    PathtoPublish: '$(outputFolder)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
