trigger:
- main

pool:
  name: default

variables:
  buildConfiguration: 'Release'
  outputFolder: '$(Agent.WorkFolder)/_build_output'
  apiProject: 'src/finance-control.Api/finance-control.Api.csproj'
  destinationFolder: 'C:\Users\Mateus\Desktop\Publish'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restaurar pacotes
- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes'
  inputs:
    command: 'restore'
    projects: '$(apiProject)'

# Compilar o projeto da API
- task: DotNetCoreCLI@2
  displayName: 'Compilar API (.NET 9)'
  inputs:
    command: 'build'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration)'

# Publicar o projeto da API
- task: DotNetCoreCLI@2
  displayName: 'Publicar API (.NET 9)'
  inputs:
    command: 'publish'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(outputFolder)'

# Copiar os arquivos para a pasta onde o IIS serve
- powershell: |
    $source = "$(outputFolder)"
    $destination = "$(destinationFolder)"

    if (!(Test-Path -Path $destination)) {
      New-Item -ItemType Directory -Path $destination | Out-Null
    }

    Write-Host "Removendo arquivos antigos em $destination..."
    Get-ChildItem -Path $destination -Recurse | Remove-Item -Force -Recurse

    Write-Host "Copiando novos arquivos de $source para $destination..."
    Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

    Write-Host "Publicação concluída com sucesso."
  displayName: 'Copiar e sobrescrever arquivos da API no IIS'

