trigger:
- main

pool:
  name: default

variables:
  buildConfiguration: 'Release'
  projectPath: 'src/finance-control.Api/finance-control.Api.csproj'
  publishDestination: 'C:\Users\Mateus\Desktop\Publish'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build API (.NET 9)'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

# ETAPA FINAL CORRIGIDA
- task: DotNetCoreCLI@2
  displayName: 'Publicar API (.NET 9) diretamente no destino'
  inputs:
    command: 'publish'
    # 1. Diga à tarefa que estamos publicando um projeto web.
    publishWebProjects: true
    # 2. Desative explicitamente a criação do zip.
    zipAfterPublish: false
    # 3. Use os argumentos para especificar o destino.
    arguments: '--configuration $(buildConfiguration) --output "$(publishDestination)"'
    # 4. (Opcional, mas bom manter) Não adicione o nome do projeto ao caminho.
    modifyOutputPath: false
