version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # UI Web do Jaeger (http://localhost:16686)
      - "4317:4317"     # OTLP gRPC (opcional, alguns casos usam direto no Jaeger)
    networks:
      - observabilidade

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
       - "5555:4317"
    depends_on:
      - jaeger
    networks:
      - observabilidade

networks:
  observabilidade:
    driver: bridge
